# Generated by Django 5.1.7 on 2025-04-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0003_reuniao_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='token',
        ),
        migrations.AddField(
            model_name='mentorados',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
